/// Currencies offered in the picker (CUR-1): ISO 4217 code and English name.
/// Names aren't translated yet.
const List<(String, String)> currencies = [
  ('AED', 'UAE Dirham'),
  ('ARS', 'Argentine Peso'),
  ('AUD', 'Australian Dollar'),
  ('BDT', 'Bangladeshi Taka'),
  ('BGN', 'Bulgarian Lev'),
  ('BHD', 'Bahraini Dinar'),
  ('BRL', 'Brazilian Real'),
  ('CAD', 'Canadian Dollar'),
  ('CHF', 'Swiss Franc'),
  ('CLP', 'Chilean Peso'),
  ('CNY', 'Chinese Yuan'),
  ('COP', 'Colombian Peso'),
  ('CZK', 'Czech Koruna'),
  ('DKK', 'Danish Krone'),
  ('DZD', 'Algerian Dinar'),
  ('EGP', 'Egyptian Pound'),
  ('EUR', 'Euro'),
  ('GBP', 'British Pound'),
  ('GHS', 'Ghanaian Cedi'),
  ('HKD', 'Hong Kong Dollar'),
  ('HUF', 'Hungarian Forint'),
  ('IDR', 'Indonesian Rupiah'),
  ('ILS', 'Israeli New Shekel'),
  ('INR', 'Indian Rupee'),
  ('IQD', 'Iraqi Dinar'),
  ('ISK', 'Icelandic Króna'),
  ('JOD', 'Jordanian Dinar'),
  ('JPY', 'Japanese Yen'),
  ('KES', 'Kenyan Shilling'),
  ('KRW', 'South Korean Won'),
  ('KWD', 'Kuwaiti Dinar'),
  ('KZT', 'Kazakhstani Tenge'),
  ('LBP', 'Lebanese Pound'),
  ('LKR', 'Sri Lankan Rupee'),
  ('MAD', 'Moroccan Dirham'),
  ('MXN', 'Mexican Peso'),
  ('MYR', 'Malaysian Ringgit'),
  ('NGN', 'Nigerian Naira'),
  ('NOK', 'Norwegian Krone'),
  ('NPR', 'Nepalese Rupee'),
  ('NZD', 'New Zealand Dollar'),
  ('OMR', 'Omani Rial'),
  ('PEN', 'Peruvian Sol'),
  ('PHP', 'Philippine Peso'),
  ('PKR', 'Pakistani Rupee'),
  ('PLN', 'Polish Złoty'),
  ('QAR', 'Qatari Riyal'),
  ('RON', 'Romanian Leu'),
  ('RSD', 'Serbian Dinar'),
  ('RUB', 'Russian Ruble'),
  ('SAR', 'Saudi Riyal'),
  ('SEK', 'Swedish Krona'),
  ('SGD', 'Singapore Dollar'),
  ('THB', 'Thai Baht'),
  ('TND', 'Tunisian Dinar'),
  ('TRY', 'Turkish Lira'),
  ('TWD', 'New Taiwan Dollar'),
  ('UAH', 'Ukrainian Hryvnia'),
  ('USD', 'US Dollar'),
  ('VND', 'Vietnamese Dong'),
  ('ZAR', 'South African Rand'),
];
